name: CI/CD Pipeline with Keploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
      
    - name: Start server in background
      run: |
        nohup node server.js > server.log 2>&1 &
        echo "Waiting for server to start..."
        sleep 10
        cat server.log

    # Keploy Integration
    - name: Install Keploy CLI
      run: |
        curl --silent -L https://keploy.io/ent/install.sh | bash
        echo "$HOME/.keploy/bin" >> $GITHUB_PATH
        
    - name: Run Keploy Test Suite
      env:
        KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
      run: |
        export KEPLOY_API_KEY=s9zKiW3cqi5v3gXdTg== && keploy test-suite --app=5523bfde-e6e9-410e-a455-70759190f35f --base-path https://taskmanager-xs8k.onrender.com/ --cloud
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: keploy-results
        path: keploy-results/

